---
title: Viash Basics
search: true
execute:
  echo: false
  output: asis
---
  
{{< include ../../includes/_language_chooser.qmd >}}
{{< include ../../includes/_python_helper.qmd >}}
 
  
## Overview

This short tutorial will touch on the basic concepts of Viash. Before getting started, make sure you've [installed Viash](/documentation/get-started/) so you can follow along with the example.

## What is Viash?

Viash is ... TODO: Add quick breakdown of the core of Viash

## Hello Viash!

Now that you're up to speed with what Viash is for, we have provided a quick example on how you can build and run a component.

### Requirements

The example targets the [Native platform](#), which means you will need to have the required packages installed on your system depending on your chosen scripting language. If you are using any of the languages on your system, there's a good chance you already meet the requirements. To get up and running quickly, we recommend using Bash.

::: {.panel-tabset}
## Bash

- A Bash Unix shell (built into Linux, macOS and WSL2)

## C\#

- A Bash Unix shell (built into Linux, macOS and WSL2)
- Download and install [.NET Core](https://dotnet.microsoft.com/download).
- Run `dotnet tool install -g dotnet-script` to enable the C# scripting functionality.

## Javascript

- A Bash Unix shell (built into Linux, macOS and WSL2)
- Download and install [Node.js](https://nodejs.org/en/).
- Execute the following command to install the required npm packages: `npm install --save needle markdown-link-extractor`

## Python

- A Bash Unix shell (built into Linux, macOS and WSL2)
- Install [Python 3.8 or newer](https://www.python.org/downloads/). You may have to install the `python-is-python3` package on Ubuntu and its derivatives.

## Scala

- A Bash Unix shell (built into Linux, macOS and WSL2)
- Install [Scala 2](https://www.scala-lang.org/download/scala2.html).

## R

- A Bash Unix shell (built into Linux, macOS and WSL2)
- Install the [R software environment](https://cran.r-project.org/mirrors.html)

:::

### Writing the script
 
Create a folder named hello_viash and follow the instructions based on your preferred scripting language

::: {.panel-tabset}

## Bash

Create script.sh

```{python}
print_file_contents("/download/hello_viash/bash/script.sh", "yaml", False)
```

## C\#

Create script.csx

```{python}
print_file_contents("/download/hello_viash/csharp/script.csx", "yaml", False)
```

## Javascript

Create script.js

```{python}
print_file_contents("/download/hello_viash/js/script.js", "yaml", False)
```

## Python

Create script.py

```{python}
print_file_contents("/download/hello_viash/python/script.py", "yaml", False)
```

## Scala

Create script.scala

```{python}
print_file_contents("/download/hello_viash/scala/script.scala", "yaml", False)
```

## R

Create script.R

```{python}
print_file_contents("/download/hello_viash/r/script.R", "yaml", False)
```

:::
### Adding the config
 
Create a file name config.vsh.yaml and add the contents below

::: {.panel-tabset}
## Bash

```{python}
print_file_contents("/download/hello_viash/bash/config.vsh.yaml", "yaml", False)
```


## C\#

```{python}
print_file_contents("/download/hello_viash/csharp/config.vsh.yaml", "yaml", False)
```

## Javascript

```{python}
print_file_contents("/download/hello_viash/js/config.vsh.yaml", "yaml", False)
```

## Python

```{python}
print_file_contents("/download/hello_viash/python/config.vsh.yaml", "yaml", False)
```

## Scala

```{python}
print_file_contents("/download/hello_viash/scala/config.vsh.yaml", "yaml", False)
```

## R

```{python}
print_file_contents("/download/hello_viash/r/config.vsh.yaml", "yaml", False)
```

:::

### Building and running

```bash
viash run config.vsh.yaml
```

## What's next?

Here are some great starting points to learn more about using Viash:

- link
- link
- link
- link