---
title: "Boolean_False"
search: true
---

An argument of the `boolean_false` type acts like an inverted `boolean` flag with a default value of `true`. When called as an argument it sets the `boolean` to `false`.

**Example:**

```yaml
arguments:
  - name: --no-log
    type: boolean_false
    description: Disable logging
    alternatives: ["-nl"]

```

## alternatives

**Type**: `String` / `List of String`

List of alternative format variations for this argument.

## description

**Type**: `String`

A description of the argument. This will be displayed with `--help`.

## info

**Type**: `Json`

Structured information. Can be any shape: a string, vector, map or even nested map.

**Example:**

```yaml
info:
  category: cat1
  labels: [one, two, three]
```

## name

**Type**: `String`

The name of the argument. Can be in the formats `--no-log`, `-n` or `no-log`. The number of dashes determines how values can be passed:  

  - `--no-log` is a long option, which can be passed with `executable_name --no-log`
  - `-n` is a short option, which can be passed with `executable_name -n`
  - `no-log` is an argument, which can be passed with `executable_name no-log`  


## type

**Type**: `String`

Specifies the type of the argument.

