---
title: "double"
search: true
execute:
  echo: false
  output: asis
---

A `double` type argument has a numeric value with decimal points

**Example:**

```yaml
arguments:
  - name: --litres
    type: double
    default: 1.5
    description: Litres of fluid to process
    alternatives: ["-l"]

```

## alternatives

**Type**: `String` / `List of String`

List of alternative format variations for this argument.

## default

**Type**: `Double` / `List of Double`

The default value when no argument value is provided. This will not work if the [`required`](#required) property is enabled.

**Example:**

```yaml
- name: --my_double
  type: double
  default: 5.8

```

## description

**Type**: `String`

A description of the argument. This will be displayed with `--help`.

## example

**Type**: `Double` / `List of Double`

An example value for this argument. If no [`default`](#default) property was specified, this will be used for that purpose.

**Example:**

```yaml
- name: --my_double
  type: double
  example: 5.8

```

## info

**Type**: `Json`

Structured information. Can be any shape: a string, vector, map or even nested map.

**Example:**

```yaml
info:
  category: cat1
  labels: [one, two, three]
```

## max

**Type**: `Double`

Maximum allowed value for this argument. If set and the provided value is higher than the maximum, an error will be produced. Can be combined with [`min`](#min) to clamp values.

**Example:**

```yaml
- name: --my_double
  type: double
  max: 80.4

```

## min

**Type**: `Double`

Minimum allowed value for this argument. If set and the provided value is lower than the minimum, an error will be produced. Can be combined with [`max`](#max) to clamp values.

**Example:**

```yaml
- name: --my_double
  type: double
  min: 25.5

```

## multiple

**Type**: `Boolean`

Treat the argument value as an array. Arrays can be passed using the delimiter `--foo=1:2:3` or by providing the same argument multiple times `--foo 1 --foo 2`. You can use a custom delimiter by using the [`multiple_sep`](#multiple_sep) property. `false` by default.

**Examples:**

```yaml
- name: --my_double
  type: double
  multiple: true

```

Here's an example of how to use this:

```bash
my_component --my_double=5.8:22.6:200.4
```

## multiple_sep

**Type**: `String`

The delimiter character for providing [`multiple`](#multiple) values. `:` by default.

**Examples:**

```yaml
- name: --my_double
  type: double
  multiple: true
  multiple_sep: ","

```

Here's an example of how to use this:

```bash
my_component --my_double=5.8,22.6,200.4
```

## name

**Type**: `String`

The name of the argument. Can be in the formats `--foo`, `-f` or `foo`. The number of dashes determines how values can be passed:  

  - `--foo` is a long option, which can be passed with `executable_name --foo=value` or `executable_name --foo value`
  - `-f` is a short option, which can be passed with `executable_name -f value`
  - `foo` is an argument, which can be passed with `executable_name value`  


## required

**Type**: `Boolean`

Make the value for this argument required. If set to `true`, an error will be produced if no value was provided. `false` by default.

**Example:**

```yaml
- name: --my_double
  type: double
  required: true

```

## type

**Type**: `String`

Specifies the type of the argument.

