---
title: "Argument Group"
search: true
order: 20
---

A grouping of the [arguments](/reference/config/arguments/#), used to display the help message.

**Example:**

```yaml
argument_groups:
  - name: "Input"
    arguments:
      - name: "--id"
        type: string
        required: true
      - name: "--input"
        type: file
        required: true
  - name: "Output"
    arguments:
      - name: "--output"
        type: file
        direction: output
        required: true
      - name: "--output_optional"
        type: file
        direction: output

```

## arguments

**Type**: `List of Argument`

**Default**: `Empty`

A list of [arguments](/reference/config/arguments/#) for this component. For each argument, a type and a name must be specified. Depending on the type of argument, different properties can be set. See these reference pages per type for more information:  

 - [string](/reference/config/arguments/string.html)
 - [file](/reference/config/arguments/file.html)
 - [integer](/reference/config/arguments/integer.html)
 - [double](/reference/config/arguments/double.html)
 - [boolean](/reference/config/arguments/boolean.html)
 - [boolean_true](/reference/config/arguments/boolean_true.html)
 - [boolean_false](/reference/config/arguments/boolean_false.html)


**Example:**

```yaml
arguments:
  - name: --foo
    type: file
    alternatives: [-f]
    description: Description of foo
    default: "/foo/bar"
    must_exist: true
    direction: output
    required: false
    multiple: true
    multiple_sep: ";"
  - name: --bar
    type: string

```

## description

**Type**: `String`

**Default**: `Empty`

A description of the argument group. This is only used for documentation. Multiline descriptions are supported.

**Example:**

```yaml
description: |
  A (multiline) description of the purpose of the arguments
  in this argument group.
```

## label

**Type**: `String`

**Default**: `Empty`

A clean version of the argument group's name. This is only used for documentation.

**Example:**

```yaml
label: "My argument group"
```

## name

**Type**: `String`

The name of the argument group.

## summary

**Type**: `String`

**Default**: `Empty`

A one-sentence summary of the argument group. This is only used for documentation.

**Example:**

```yaml
summary: "Arguments related to functionality XYZ"
```
