---
title: "Links"
search: true
---

Links to external resources related to the component.

**Example:**

```yaml
repository: "https://github.com/viash-io/viash"
docker_registry: "https://ghcr.io"
homepage: "https://viash.io"
documentation: "https://viash.io/reference/"
issue_tracker: "https://github.com/viash-io/viash/issues"

```

## docker_registry

**Type**: `String`

**Default**: `Empty`

Docker registry url.

:::{.callout-note}
When the `docker_registry` field is left empty in a component's `.functionality.links` [configuration](/reference/config/functionality.html), the value of `.links.repository` in the [project config](/reference/projectConfig/#) will be copied during build.
:::



**Example:**

```yaml
docker_registry: "https://ghcr.io"
```

## documentation

**Type**: `String`

**Default**: `Empty`

Documentation website url.

**Example:**

```yaml
documentation: "https://viash.io/reference/"
```

## homepage

**Type**: `String`

**Default**: `Empty`

Homepage website url.

**Example:**

```yaml
homepage: "https://viash.io"
```

## issue_tracker

**Type**: `String`

**Default**: `Empty`

Issue tracker url.

**Example:**

```yaml
issue_tracker: "https://github.com/viash-io/viash/issues"
```

## repository

**Type**: `String`

**Default**: `Empty`

Source repository url.

:::{.callout-note}
When the `repository` field is left empty in a component's `.functionality.links` [configuration](/reference/config/functionality.html), the value of `.links.repository` in the [project config](/reference/projectConfig/#) will be copied during build.
:::



**Example:**

```yaml
repository: "https://github.com/viash-io/viash"
```
