---
title: Advanced pipeline
order: 40
---



## Creating the modules

The sections below describe how to create the VDSL3 modules in preparation for creating the pipeline. 

### Preparation

create a new folder named advanced pipeline, add src folder with a nextflow_module folder inside. Now create three folders inside nextflow_module folder, one per component needed for the pipeline:

- `combine_columns`
- `remove_comments`
- `take_columns`


The folder structure should look like this now:

```
advanced_pipeline
└── src
    └── nextflow_modules
        ├── combine_columns
        ├── remove_comments
        └── take_column
```


1. Target directory where the modules are located
2. Include the modules from the `target` directory
3. Create a channel based on the `input` parameter's path
4. Assign a unique ID to each event using [`map{}`](https://www.nextflow.io/docs/latest/operator.html#map)
5. Run `remove_comments` to remove the comments from the TSV
6. Extract a single column from TSV by running `take_column`
7. Combine all events into a single List event using [`toList()`](https://www.nextflow.io/docs/latest/operator.html#tolist)
8. Add **unique ID** to the tuple
9. Concatenate the TSVs into one by running the `combine_columns` module with [auto publishing](/reference/config/platforms/NextflowVdsl3Platform.html#auto) enabled using the `auto` directive 
10. View the channel contents bu printing it to the console using [`view()`](https://www.nextflow.io/docs/latest/operator.html?highlight=view#view)

## Running the pipeline

Before being able to run the pipeline, you'll need some TSV files to work with. Download the files below and place them in a new directory named **data** in the root of **advanced_pipeline**.

Now run the following command to run the pipeline using Nextflow:

```bash
nextflow run main.nf --input "data/file?.tsv" --publishDir output
```

You should get an output similar to this:

```
N E X T F L O W  ~  version 22.04.3
Launching `workflows/310-realistic_pipeline/main.nf` [stupefied_saha] DSL2 - revision: 6669aefc6c
[93/232aba] Submitted process > remove_comments:remove_comments_process (2)
[ef/a28e89] Submitted process > remove_comments:remove_comments_process (1)
[63/279f98] Submitted process > take_column:take_column_process (1)
[50/2a17ef] Submitted process > take_column:take_column_process (2)
[8d/6eeff5] Submitted process > combine_columns:combine_columns_process
Output: [combined, /home/runner/work/viash_nxf_course/viash_nxf_course/work/8d/6eeff571e9ff2c5389851c6ab3001c/combined.combine_columns.output]
```

You can find the final TSV in the **output** directory:

```tsv
# this is a header		
# this is also a header		
one     0.11	123
two	    0.23	456
three	0.35	789
four	0.47	123
```

## Todo: add

* Copy guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
* Use template repository instead of download buttons

* New content:
  - How to use a module in a pipeline.
  - Specify that we assume the user knows how to write a Nextflow pipeline
  - Dynamic behaviour (.run()): dynamic directives and auto helper.
  - Nextflow Viash config
  - Showcase pre-existing pipeline, e.g. guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
  - Todo: update to latest VDSL3 practices. Let the targetDir use the rootDir. Use the newer WorkflowHelper helper functions.
