---
title: "Viash 0.7.4"
subtitle: "Minor bug fixes and minor improvements to VDSL3"
date: "2023-05-31"
categories: [ New Release ]
author: Viash Team
---

## What's new?

Some small fixes and consistency improvements.
A few Quality of Life improvements were made e.g. to override the Docker `entrypoint` when working with Nextflow and providing default labels when building a Nextflow workflow.

## Full changelog

### NEW FUNCTIONALITY

* Add default labels in Nextflow config files that set default values for cpu and memory settings (PR #412). Values are more or less logarithmically spaced (1, 2, 5, 10, ...).

* `Author`: Added `info` field to authors. Deprecated `props` field (PR #423).

* `viash config view` and `viash ns list`: Set the `.info.output` path when a platform argument is provided.

* `viash ns exec`: Added two more fields:

  - `{output}`: path to the destination directory when building the component
  - `{abs-output}`: absolute path to the destination directory when building the component

* `DockerPlatform`: Add `entrypoint` and `cmd` parameters to the docker platform config that allows overriding the default docker container settings (PR #432).

### MINOR CHANGES

* `Nextflow VDSL3`:
  - Add profiles to the Nextflow Config file when the main script is a `NextflowScript` (#408).
  - Add a `script` parameter in Nextflow Config file to add a single string or list of strings to the `nextflow.config` (PR #430).

* `Scripts`: Remove the `entrypoint` parameter for all script types except `NextflowScript` (#409). All these scripts had to check individually whether the parameter was unset, now it can be done in the `Script` apply method.

* `schema export`:
  - Restructure Nextflow-Directives, -Auto and -Config into a `nextflowParameters` group (PR #412). Previously only NextflowDirectives was exposed.
  - Restructure the format to group authors & computational requirements together with functionality (PR #426).
  - Restructure the Viash Config and Project Config pages under a `config` category (PR #426).
  - Add references in Functionality and Nextflow VDSL3 to the new documentation pages (PR #426).
  - Add description and/or examples for platforms and requirements (PR #428).

### BUG FIXES

* `viash config inject`: Fix an empty line being added at the script start for each time `viash config inject` was run (#377).

* `WorkflowHelper`: Fixed an issue where passing a remote file URI (for example `http://` or `s3://`) as `param_list` caused `No such file` errors.

* `BashWrapper`: Fix escaping of the included script where a line starting with a pipe character with optional leading spaces is stripped of the leading spaces and pipe character.
  This was quite unlikely to happen except when `viash config inject` was called on a Nextflow Script, which lead to no real config code being injected however workflows were getting corrupted. (#421)

* `Deprecation testbench`: Add missing classes to be checked (PR #426).

