---
title: "Viash 0.9.0-RC2"
subtitle: "Restructure the config and change some default values"
date: "2024-02-23"
categories: [ New Release ]
author: Viash Team
---

## What's new?

The `.functionality` layer has been removed from the config and all fields have been moved to the top layer.
The default `multiple_sep` has been changed from `:` to `;` to avoid conflicts with paths like `s3://foo/bar`.

## Full changelog

### BREAKING CHANGES

* `arguments`: Change default `multiple_sep` from `:` to `;` to avoid conflicts with paths like `s3://foo/bar` (PR #645).
  The previous behaviour of using `multiple_sep: ":"` can be achieved by adding a config mod to the `_viash.yaml`:
  ```yaml
  config_mods: |
    .functionality.argument_groups[true].arguments[.multiple == true].multiple_sep := ":"
  ```

* `functionality`: Remove the `functionality` layer from the config and move all fields to the top layer (PR #649).

### MINOR CHANGES

* `package config`: Renamed `project config` to `package config` (PR #636). Now that we start using the config more, we came to the conclusion that "package" was better suited that "project".

* `ns exec`: Added an extra field `{name}` to replace `{functionality-name}` (PR #649). No immediate removal of the old field is planned, but it is deprecated.

* `BashWrapper`: Added meta-data field `meta_name` as a replacement for `meta_functionality_name` (PR #649). No immediate removal of the old field is planned, but it is deprecated.

### BUG FIXES

* `schema`: Don't require undocumented fields to set default values and add the `links` and `reference` fields to functionality as they were not meant only to be in the project config (PR #636).

