project:
  type: website
  output-dir: _site
  preview:
    port: 8000
    browser: false

website:
  title: "Viash"
  image: "viash.png"
  favicon: "favicon.png"
  google-analytics: "G-GDS2XT0DDG"
  open-graph: true
  site-url: https://viash.io
  repo-url: https://github.com/viash-io/website
  repo-actions: [edit, source, issue]
  page-navigation: true
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "Privacy Policy"
        href: privacy.qmd
  navbar:
    background: light
    logo: viash.png
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Installation"
        href: installation/index.qmd
      - text: "Quickstart"
        href: quickstart/index.qmd
      - text: "Guide"
        href: guide/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      # - text: "Gallery"
      #   href: gallery/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Help"
        menu:
          # - text: "Terminology"
          #   icon: "journal-text"
          #   href: help/terminology.qmd
          - text: "Report a Viash issue"
            icon: "bug"
            href: "https://github.com/viash-io/viash/issues"
          - text: "Report a website issue"
            icon: "bug"
            href: "https://github.com/viash-io/website/issues"
          - text: "Cheat sheet"
            icon: "card-list"
            href: cheatsheet/viash_cheatsheet_v1_2.pdf
    right:
      - icon: github
        href: https://github.com/viash-io/viash
        aria-label: Viash GitHub

  sidebar:
    - id: guide
      collapse-level: 3
      contents: 
        - auto: guide

    - id: reference
      title: "Reference"
      collapse-level: 3
      contents:
        - auto: reference

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    link-external-icon: false
    link-external-newwindow: true
    code-copy: true
    code-overflow: scroll
    css: styles.css
    include-after-body: js.html
    mermaid-format: js

execute:
  freeze: auto

engine: knitr