functionality:
  name: generate_version_blog_pages
  description: |
    The script takes a changelog.md file and splits it into multiple quarto pages
    Some formatting is expected to extract titles, version number, etc.
  arguments:
    - name: "--input"
      type: file
      alternatives: "-i"
      direction: input
      description: The changelog.md to use as input
      required: true
      must_exist: true
    - name: "--output"
      type: file
      alternatives: "-o"
      direction: output
      description: Base path to use to store the pages, should match 'blog/posts'
    - name: "--verbose"
      type: boolean_true
      alternatives: "-v"
      description: Print output file content to the terminal
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: bash_script
      path: test.sh
    - path: test_changelog.md
platforms:
  - type: native
