---
title: "Nextflow Auto"
search: true
---

Automated processing flags which can be toggled on or off.

## publish

**Type**: `Either Boolean or String`

**Default**: `False`

If `true`, the module's outputs are automatically published to `params.publishDir`.
If equal to `"state"`, also a `.state.yaml` file will be published in the publish dir.
Will throw an error if `params.publishDir` is not defined.

Default: `false`.


## simplifyInput

**Type**: `Boolean`

**Default**: `True`

If `true`, an input tuple only containing only a single File (e.g. `["foo", file("in.h5ad")]`) is automatically transformed to a map (i.e. `["foo", [ input: file("in.h5ad") ] ]`).

Default: `true`.


## simplifyOutput

**Type**: `Boolean`

**Default**: `False`

If `true`, an output tuple containing a map with a File (e.g. `["foo", [ output: file("out.h5ad") ] ]`) is automatically transformed to a map (i.e. `["foo", file("out.h5ad")]`).

Default: `false`.


## transcript

**Type**: `Boolean`

**Default**: `False`

If `true`, the module's transcripts from `work/` are automatically published to `params.transcriptDir`.
If not defined, `params.publishDir + "/_transcripts"` will be used.
Will throw an error if neither are defined.

Default: `false`.

