---
title: "Git Repository"
search: true
---

A Git repository where remote dependency components can be found.

**Examples:**

Example without `name` field in case used in `.dependencies`

```yaml
type: git
uri: git+https://github.com/openpipelines-bio/openpipeline.git
tag: 0.8.0

```

Example without `name` field in case used in `.dependencies`

```yaml
type: git
uri: git+https://gitlab.com/viash-io/viash.git
tag: 0.7.1
path: src/test/resources/testns

```

Example with `name` field in case used in `.repositories`

```yaml
name: openpipeline
type: git
uri: git+https://github.com/openpipelines-bio/openpipeline.git
tag: 0.8.0

```

Example with `name` field in case used in `.repositories`

```yaml
name: viash-testns
type: git
uri: git+https://gitlab.com/viash-io/viash.git
tag: 0.7.1
path: src/test/resources/testns

```

## name

**Type**: `String`

:::{.callout-warning}
When defining repositories under `.repositories`, the repository definition needs a `name` field so it can be refered to from a dependency.

When defining a repository directly in a dependency under `.dependencies`, the `name` field must be omitted.
:::

The identifier used to refer to this repository from dependencies.

## path

**Type**: `String`

**Default**: `Empty`

Defines a subfolder of the repository to use as base to look for the dependency components.

## tag

**Type**: `String`

**Default**: `Empty`

Defines which version of the dependency component to use. Typically this can be a specific tag, branch or commit hash.

## type

**Type**: `String`

Defines the repository as a Git repository.

## uri

**Type**: `String`

The URI of the Git repository.

**Example:**

```yaml
uri: "git+https://github.com/openpipelines-bio/openpipeline.git"
```
