---
title: "Repository"
search: true
order: 90
---

Specifies a repository where dependency components can be found.

 - [local](/reference/config/repositories/localRepository.html)
 - [git](/reference/config/repositories/gitRepository.html)
 - [github](/reference/config/repositories/githubRepository.html)
 - [vsh](/reference/config/repositories/viashhubRepository.html)


**Examples:**

Definition of a repository in the component config or package config.

```yaml
repositories:
  - name: openpipelines-bio
    type: github
    repo: openpipelines-bio/modules
    tag: 0.3.0

```

Definition of dependency with a fully defined repository

```yaml
dependencies:
  - name: qc/multiqc
    repository: 
      type: github
      repo: openpipelines-bio/modules
      tag: 0.3.0

```

## path

**Type**: `String`

**Default**: `Empty`

Defines a subfolder of the repository to use as base to look for the dependency components.

## tag

**Type**: `String`

**Default**: `Empty`

Defines which version of the dependency component to use. Typically this can be a specific tag, branch or commit hash.

## type

**Type**: `String`

Defines the repository type. This determines how the repository will be fetched and handled.
