---
title: "Local Repository"
search: true
---

Defines a locally present and available repository.
This can be used to define components from the same code base as the current component.
Alternatively, this can be used to refer to a code repository present on the local hard-drive instead of fetchable remotely, for example during development.


**Examples:**

Example without `name` field in case used in `.dependencies`

```yaml
type: local
path: /additional_code/src

```

Example with `name` field in case used in `.repositories`

```yaml
name: my_local_code
type: local
path: /additional_code/src

```

## name

**Type**: `String`

:::{.callout-warning}
When defining repositories under `.repositories`, the repository definition needs a `name` field so it can be refered to from a dependency.

When defining a repository directly in a dependency under `.dependencies`, the `name` field must be omitted.
:::

The identifier used to refer to this repository from dependencies.

## path

**Type**: `String`

**Default**: `Empty`

Defines a subfolder of the repository to use as base to look for the dependency components.

## tag

**Type**: `String`

**Default**: `Empty`

Defines which version of the dependency component to use. Typically this can be a specific tag, branch or commit hash.

## type

**Type**: `String`

Defines the repository as a locally present and available repository.
