---
title: "Package Config"
search: true
---

A Viash package configuration file. It's name should be `_viash.yaml`.

**Example:**

```yaml
viash_version: 0.9.0
source: src
target: target
version: 1.0
organization: viash-io
links:
  repository: 'https://github.com/viash-io/viash'
  docker_registry: 'ghcr.io'
config_mods: |
  .runners[.type == 'nextflow'].directives.tag := '$id'
  .runners[.type == 'nextflow'].config.script := 'includeConfig("configs/custom.config")'

```

## authors

**Type**: `List of Author`

**Default**: `Empty`

The authors of the package.

**Example:**

```yaml
authors:
  - name: Jane Doe
    role: [author, maintainer]
    email: jane@doe.com
    info:
      github: janedoe
      twitter: janedoe
      orcid: XXAABBCCXX
      groups: [ one, two, three ]
  - name: Tim Farbe
    roles: [author]
    email: tim@far.be

```

## config_mods

**Type**: `String` / `List of String`

**Default**: `Empty`

Which config mods to apply.

**Example:**

```yaml
config_mods: ".name := 'foo'"
```

## description

**Type**: `String`

**Default**: `Empty`

A description of the package.

**Example:**

```yaml
description: My package
```

## info

**Type**: `Json`

**Default**: `Empty`

Structured information. Can be any shape: a string, vector, map or even nested map.

**Example:**

```yaml
info:
  twitter: wizzkid
  classes: [ one, two, three ]
```

## keywords

**Type**: `List of String`

**Default**: `Empty`

The keywords of the package.

**Example:**

```yaml
keywords: [ bioinformatics, genomics ]
```

## license

**Type**: `String`

**Default**: `Empty`

The license of the package.

:::{.callout-note}
When the `license` field is left empty in a component's [configuration](/reference/config/#), the value of `.version` in the package config will be copied during build.
:::



**Example:**

```yaml
license: MIT
```

## links

**Type**: `Links`

**Default**: `Empty`

External links of the package.

**Example:**

```yaml
links:
  repository: "https://github.com/viash-io/viash"
  docker_registry: "https://ghcr.io"
  homepage: "https://viash.io"
  documentation: "https://viash.io/reference/"
  issue_tracker: "https://github.com/viash-io/viash/issues"

```

## name

**Type**: `String`

**Default**: `Empty`

The name of the package.

**Example:**

```yaml
name: my_package
```

## organization

**Type**: `String`

**Default**: `Empty`

The organization of the package.

:::{.callout-note}
When the `organization` field is left empty in a component's [configuration](/reference/config/#), the value of `.version` in the package config will be copied during build.
:::



**Example:**

```yaml
organization: viash-io
```

## references

**Type**: `References`

**Default**: `Empty`

References to external resources related to the package.

**Example:**

```yaml
references:
  doi: 10.1000/xx.123456.789
  bibtex: |
    @article{foo,
      title={Foo},
      author={Bar},
      journal={Baz},
      year={2024}
    }

```

## repositories

**Type**: `List of RepositoryWithName`

**Default**: `Empty`

Common repository definitions for component dependencies.

:::{.callout-note}
Any repositories defined under `.repositories` in the project config will be prepended to the list of repositories defined in a component's `.repositories` field.
:::



**Example:**

```yaml
repositories:
  - name: openpipelines-bio
    type: github
    uri: openpipelines-bio/modules
    tag: 0.3.0

```

## source

**Type**: `String`

**Default**: `Empty`

Which source directory to use for the `viash ns` commands.

**Example:**

```yaml
source: src
```

## target

**Type**: `String`

**Default**: `Empty`

Which target directory to use for `viash ns build`.

**Example:**

```yaml
target: target
```

## version

**Type**: `String`

**Default**: `Empty`

The version of the package.

:::{.callout-note}
When the `version` field is left empty in a component's [configuration](/reference/config/#), the value of `.version` in the package config will be copied during build.
:::



**Example:**

```yaml
version: 0.1.0
```

## viash_version

**Type**: `String`

**Default**: `Empty`

Which version of Viash to use.

**Example:**

```yaml
viash_versions: 0.6.4
```
