---
title: "Viash 0.5.10"
subtitle: "Rework of the Viash helper components"
date: "2022-03-15"
categories: [ New Release ]
author: Viash Team
---

## What's new?

The `viash_install`, `viash_build`, `viash_test` and `viash_push` components have been reworked.

## Full changelog

### MAJOR CHANGES

* `viash_install`:
  - Added `--log_prefix`: This prefix is used to determine the path of the log files for `viash_build`, `viash_test` and `viash_push`.
  - Added `--organization`: Id of the organisation to be used in the Docker image name, i.e. `<registry>/<organization>/<namespace><namespace_sep><name>`.
  - Added `--target_image_source`: Url to the Git repo in which this project resides.
  - Removed `--log`.

* `viash_build`:
  - Reduce code duplication by contructing the command with Bash Arrays.
  - Renamed `--platforms` to `--platform`.
  - Added `--organization`: Id of the organisation to be used in the Docker image name, i.e. `<registry>/<organization>/<namespace><namespace_sep><name>`.
  - Added `--target_image_source`: Url to the Git repo in which this project resides.
  - Changed default of `--log` from `log.txt` to `.viash_build_log.txt`.
  - Added `--verbose`: Print out the underlying `viash ns build` command before running it.

* `viash_test`:
  - Reduce code duplication by contructing the command with Bash Arrays.
  - Renamed `--platforms` to `--platform`.
  - Added `--organization`: Id of the organisation to be used in the Docker image name, i.e. `<registry>/<organization>/<namespace><namespace_sep><name>`.
  - Added `--target_image_source`: Url to the Git repo in which this project resides.
  - Changed default of `--log` from `log.txt` to `.viash_test_log.txt`.
  - Changed default of `--tsv` from `log.tsv` to `.viash_test_log.tsv`.
  - Added `--verbose`: Print out the underlying `viash ns test` command before running it.

* `viash_push`:
  - Reduce code duplication by contructing the command with Bash Arrays.
  - Added `--organization`: Id of the organisation to be used in the Docker image name, i.e. `<registry>/<organization>/<namespace><namespace_sep><name>`.
  - Changed default of `--log` from `log.txt` to `.viash_push_log.txt`.
  - Added `--verbose`: Print out the underlying `viash ns build` command before running it.

### MINOR CHANGES

* `NextflowPlatform`: Added the `organization` field to the nextflow platform as well.

