---
title: "Viash Config View"
search: true
---

View the config file after parsing.

**Usage:**

`viash config view config.vsh.yaml`

| Argument | Description | Type |
|-|:----|-:
| `config` | A viash config file (example: `config.vsh.yaml`). This argument can also be a script with the config as a header. **This is a required argument.** | `String` |
| `--config_mod`, `-c` | Modify a viash config at runtime using [dynamic config modding](/reference/config_mods/#). | `List[String]` |
| `--engine` | A regex to determine which engines amongst those specified in the config to use. If this is not provided, all engines will be used. If no engines are defined in the config, the native engine will be used. | `String` |
| `--format`, `-f` | Which output format to use. | `String` |
| `--parse_argument_groups` | DEPRECATED. This is now always enabled. Whether or not to postprocess each component's [argument groups](/reference/config/#argument_groups). | `Boolean` |
| `--platform`, `-p` | Deprecated. Use --runner and --engine instead. Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | `String` |
| `--runner` | Specifies which runner amongst those specified in the config to use. If this is not provided, the first runner will be used. If no runners are defined in the config, the executable runner will be used. | `String` |
| `--help`, `-h` | Show help message |  |

