---
title: "Viash Run"
search: true
---

Executes a viash component from the provided viash config file. viash generates a temporary executable and immediately executes it with the given parameters.

**Usage:**

`viash run config.vsh.yaml [-p docker] [-k true/false]  -- [arguments for script]`

| Argument | Description | Type |
|-|:----|-:
| `config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. **This is a required argument.** | `String` |
| `--config_mod`, `-c` | Modify a viash config at runtime using [dynamic config modding](/reference/config_mods/#). | `List[String]` |
| `--cpus` | The maximum number of (logical) cpus a component is allowed to use. | `Int` |
| `--keep`, `-k` | Whether or not to keep temporary files. By default, files will be deleted if all goes well but remain when an error occurs. By specifying --keep true, the temporary files will always be retained, whereas --keep false will always delete them. The temporary directory can be overwritten by setting defining a VIASH_TEMP directory. | `String` |
| `--memory` | The maximum amount of memory a component is allowed to allocate. Unit must be one of B, KB, MB, GB, TB or PB. | `String` |
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | `String` |
| `--help`, `-h` | Show help message |  |

