functionality:
  name: generate_reference_cli_pages
  description: |
    The script reads the viash cli schema json schema and splits it into multiple quarto pages
  arguments:
    - name: "--input"
      type: file
      alternatives: "-i"
      direction: input
      description: The json file to use as input
      required: true
      must_exist: true
    - name: "--output"
      type: file
      alternatives: "-o"
      direction: output
      default: 'reference/cli'
      description: Base path to use to store the pages
  resources:
    - type: python_script
      path: script.py
    - type: file
      path: ../config_pages_settings.yaml
    - type: file
      path: template_cli_page.j2.qmd
engines:
  - type: native
runners:
  - type: executable
