---
title: "Viash 0.7.1"
subtitle: "Minor improvements to VDSL3 and schema functionality."
date: "2023-03-08"
categories: [ New Release ]
author: Viash Team
---

## What's new?

This is a minor release which improves caching in VDSL3 components and changes the formats of the schema files for the Viash config and CLI.

## Full changelog

### MINOR CHANGES

* `DataflowHelper`: Add assertions and `def`s.

### BUG FIXES

* `VDSL3`: Only the first two elements from an event in a channel are now passed to a process. This avoids calculating cache entries based on arguments that are not used by the process, causing false-negative cache misses.

* `config_schema`:
  - Correct some incorrect markdown tags.
  - Add project config.
  - Correct documentation/markdown tags to the correct order.
  - Add summary description and example for 'resource' and 'argument', to be used on the reference website.
  - Add documentation for the Nextflow directives.

* `cli_schema`: Correct documentation/markdown tags to the correct order.

