---
title: Docker Volumes
search: true
execute:
  echo: false
  output: asis
---

Viash automatically creates a [Docker volume](https://docs.docker.com/storage/volumes/) for components and executables with a Docker backend if a [`file` argument](/documentation/reference/config/arguments/file.html) exists in the [config file](/documentation/reference/config/overview.html). This allows your script to read and write files as if working with them natively.  

The full mount path is `/viash_automount/ABSOLUTE_PATH_TO_FILE_DIRECTORY`.  

By default, files created and modified by a Docker container are owned by **root**. By default, Viash automatically changes the owner of any files defined in the config file to the user running the executable. This behaviour can be overridden by setting the [chown](/documentation/reference/config/platforms/DockerPlatform.html#chown) setting to `false` in your config file.

:::{.callout-important}
Any files your script generates that are not defined as `file` arguments will still be owned by **root** as Viash won't have any knowledge of them.
:::