---
title: Setup Strategies
search: true
execute:
  echo: false
  output: asis
---

Viash supports the use of several different Docker setup strategies. You can choose what strategy to build an executable with when using a Docker backend by passing the `--setup` option followed by one of the strategies below.  

For example:

```bash
viash build config.vsh.yaml -p docker --setup alwayscachedbuild
```

## Build

* `alwaysbuild` / `build` / `b`: Always build the image from the dockerfile. This is the default setup strategy.
* `alwayscachedbuild` / `cachedbuild` / `cb`: Always build the image from the dockerfile, with caching enabled.
* `ifneedbebuild`: Build the image if it does not exist locally.
* `ifneedbecachedbuild`: Build the image with caching enabled if it does not exist locally.

## Pull

* `alwayspull` / `pull` / `p`: Try to pull the container from [Docker Hub](https://hub.docker.com) or the [specified docker registry](/documentation/reference/config/platforms/DockerPlatform.html#registry).
* `alwayspullelsebuild` / `pullelsebuild`: Try to pull the image from a registry and build it if it doesn't exist.
* `alwayspullelsecachedbuild` / `pullelsecachedbuild`: Try to pull the image from a registry and build it with caching if it doesn't exist.
* `ifneedbepull`: If the image does not exist locally, pull the image.
* `ifneedbepullelsebuild` If the image does not exist locally, pull the image. If the image does exist, build it.
* `ifneedbepullelsecachedbuild`: If the image does not exist locally, pull the image. If the image does exist, build it with caching enabled.

## Push

* `push`: Push the container to [Docker Hub](https://hub.docker.com)  or the [specified docker registry](/documentation/reference/config/platforms/DockerPlatform.html#registry).
* `pushifnotpresent` Push the container to [Docker Hub](https://hub.docker.com) or the [specified docker registry](/documentation/reference/config/platforms/DockerPlatform.html#registry) if the [specified tag](/documentation/reference/config/platforms/DockerPlatform.html#tag) does not exist yet.

## Do nothing

* `donothing` / `meh`: Do not build or pull anything.