---
title: "Viash 0.8.2"
subtitle: "Minor changes and bug fixes"
date: "2023-12-14"
categories: [ New Release ]
author: Viash Team
---

## What's new?

This release fixes a few bugs regarding dependencies and how the Nextflow platform handles Paths.

## Full changelog

### MINOR CHANGES

* `NextflowTestHelper`: Do not hardcode a version of Nextflow in the testbench, 
  but use the version of Nextflow that is installed on the system (PR #593).

* GitHub Actions: Test different versions of Nextflow (22.04.5, latest, and latest-edge) (PR #593).
  Testing the latest Edge version of Nextflow will allow us to catch notice changes in Nextflow earlier.

* Updates to the documentation and templates in the Git repo (#598, PR #600):

  - Add contributing guidelines.

  - Add issue templates.

  - Reworked the pull request template.

### BUG FIXES

* `config`: Fix the main level of a component config not enforcing strict mode and instead allowing any field to be specified (PR #585).

* `dependencies`: Allow the user to define a local dependency with specifying `repository: local` as sugar syntax (PR #609). A local repository is the default value so it's not required to be filled in, but allowing it with a sensible sugar syntax makes sense.

* `Repositories`: Fix a structural issue where a repository defined directly in a `dependency` would require the `name` field to be set (PR #607). Repository variants are created with and without the `name` field. Repositories under `.functionality.dependencies[]` use repositories without the `name` field, while repositories under `.functionality.repositories[]` use repositories with the `name` field.

* `NextflowPlatform`: Do not resolve remote paths relative to the --param_list file (PR #592).

* `NextflowPlatform`: Allow finding `.build.yaml` file when worktree contains a directory that is a symlink (PR #611). 

