---
title: "Python Requirements"
search: true
execute:
  echo: false
  output: asis
---

Specify which Python packages should be available in order to run the component.

**Example:**

```yaml
setup:
  - type: python
    pip: numpy
    github: [ jkbr/httpie, foo/bar ]
    url: "https://github.com/some_org/some_pkg/zipball/master"

```

## bazaar

**Type**: `String` / `List of String`

Specifies which packages to install using a Bazaar URI.

**Example:**

```yaml
bazaar: [ http://bazaar.launchpad.net/some_pkg/some_pkg/release-0.1 ]
```

## git

**Type**: `String` / `List of String`

Specifies which packages to install using a Git URI.

**Example:**

```yaml
git: [ https://some.git.repository/org/repo ]
```

## github

**Type**: `String` / `List of String`

Specifies which packages to install from GitHub.

**Example:**

```yaml
github: [ jkbr/httpie ]
```

## gitlab

**Type**: `String` / `List of String`

Specifies which packages to install from GitLab.

**Example:**

```yaml
gitlab: [ foo/bar ]
```

## mercurial

**Type**: `String` / `List of String`

Specifies which packages to install using a Mercurial URI.

**Example:**

```yaml
mercurial: [ https://hg.myproject.org/MyProject/#egg=MyProject ]
```

## packages

**Type**: `String` / `List of String`

Specifies which packages to install from pip.

**Example:**

```yaml
packages: [ numpy ]
```

## pip

**Type**: `String` / `List of String`

Specifies which packages to install from pip.

**Example:**

```yaml
pip: [ numpy ]
```

## pypi

**Type**: `String` / `List of String`

Specifies which packages to install from PyPI using pip.

**Example:**

```yaml
pypi: [ numpy ]
```

## script

**Type**: `String` / `List of String`

Specifies a code block to run as part of the build.

**Example:**

```yaml
script: |
  print("Running custom code")
  x = 1 + 1 == 2
```

## svn

**Type**: `String` / `List of String`

Specifies which packages to install using an SVN URI.

**Example:**

```yaml
svn: [ http://svn.repo/some_pkg/trunk/#egg=SomePackage ]
```

## type

**Type**: `String`

Specifies the type of the requirement specification.

## upgrade

**Type**: `Boolean`

Sets the `--upgrade` flag when set to true. Default: true.

## url

**Type**: `String` / `List of String`

Specifies which packages to install using a generic URI.

**Example:**

```yaml
url: [ https://github.com/some_org/some_pkg/zipball/master ]
```

## user

**Type**: `Boolean`

Sets the `--user` flag when set to true. Default: false.

