---
title: "R Requirements"
search: true
---

Specify which R packages should be available in order to run the component.

**Example:**

```yaml
setup: 
  - type: r
    cran: anndata
    bioc: [ AnnotationDbi, SingleCellExperiment ]
    github: rcannood/SCORPIUS

```

## bioc

**Type**: `String` / `List of String`

Specifies which packages to install from BioConductor.

**Example:**

```yaml
bioc: [ AnnotationDbi ]
```

## bioc_force_install

**Type**: `Boolean`

Forces packages specified in `bioc` to be reinstalled, even if they are already present in the container. Default: false.

**Example:**

```yaml
bioc_force_install: false
```

## bitbucket

**Type**: `String` / `List of String`

Specifies which packages to install from Bitbucket.

**Example:**

```yaml
bitbucket: [ org/package ]
```

## cran

**Type**: `String` / `List of String`

Specifies which packages to install from CRAN.

**Example:**

```yaml
cran: [ anndata, ggplot2 ]
```

## git

**Type**: `String` / `List of String`

Specifies which packages to install using a Git URI.

**Example:**

```yaml
git: [ https://some.git.repository/org/repo ]
```

## github

**Type**: `String` / `List of String`

Specifies which packages to install from GitHub.

**Example:**

```yaml
github: [ rcannood/SCORPIUS ]
```

## gitlab

**Type**: `String` / `List of String`

Specifies which packages to install from GitLab.

**Example:**

```yaml
gitlab: [ org/package ]
```

## packages

**Type**: `String` / `List of String`

Specifies which packages to install from CRAN.

**Example:**

```yaml
packages: [ anndata, ggplot2 ]
```

## script

**Type**: `String` / `List of String`

Specifies a code block to run as part of the build.

**Example:**

```yaml
script: |
  cat("Running custom code
")
  install.packages("anndata")
```

## svn

**Type**: `String` / `List of String`

Specifies which packages to install using an SVN URI.

**Example:**

```yaml
svn: [ https://path.to.svn/group/repo ]
```

## type

**Type**: `String`

Specifies the type of the requirement specification.

## url

**Type**: `String` / `List of String`

Specifies which packages to install using a generic URI.

**Example:**

```yaml
url: [ https://github.com/hadley/stringr/archive/HEAD.zip ]
```

