---
title: viash config
search: true
execute:
  echo: false
  output: asis
---

## viash config view

View the config file after parsing.

**Usage:**

`viash config view config.vsh.yaml`

| Argument | Description | Type |
|-|:----|-:
| `config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. **This is a required argument.** | `String` |
| `--config_mod`, `-c` | Modify a viash config at runtime using [dynamic config modding](/documentation/reference/config/config-modding.html). | `List[String]` |
| `--format`, `-f` | Which output format to use. | `String` |
| `--parse_argument_groups` | Whether or not to postprocess each component's [argument groups](/documentation/reference/config/functionality.html#argument_groups). | `Boolean` |
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | `String` |
| `--help`, `-h` | Show help message |  |


## viash config inject

Inject a Viash header into the main script of a Viash component.

**Usage:**

`viash config inject config.vsh.yaml`

| Argument | Description | Type |
|-|:----|-:
| `config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. **This is a required argument.** | `String` |
| `--config_mod`, `-c` | Modify a viash config at runtime using [dynamic config modding](/documentation/reference/config/config-modding.html). | `List[String]` |
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | `String` |
| `--help`, `-h` | Show help message |  |


