---
title: "Viash (Python)"
---

## viash run

Executes a viash component from the provided viash config file. viash generates a temporary executable and immediately executes it with the given parameters.  

  

**Usage:**  

`viash run config.vsh.yaml [-p docker] [-k true/false]  -- [arguments for script]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. | String |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--keep`, `-k` | Whether or not to keep temporary files. By default, files will be deleted if all goes well but remain when an error occurs. By specifying --keep true, the temporary files will always be retained, whereas --keep false will always delete them. The temporary directory can be overwritten by setting defining a VIASH_TEMP directory. | String |


## viash build

Build an executable from the provided viash config file.  

  

**Usage:**  

`viash build config.vsh.yaml -o output [-p docker] [-m] [-s]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. | String |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--meta`, `-m` | Print out some meta information at the end. | Boolean |
| `--write_meta`, `-w` | Write out some meta information to RESOURCES_DIR/viash.yaml at the end. | Boolean |
| `--output` | Path to directory in which the executable and any resources is built to. Default: "output/". | String |
| `--setup` | Which setup strategy for creating the container to use [Docker Platform only]. | String |
| `--push` | Whether or not to push the container to a Docker registry [Docker Platform only]. | Boolean |


## viash test

Test the component using the tests defined in the viash config file.  

  

**Usage:**  

`viash test config.vsh.yaml [-p docker] [-k true/false]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. | String |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--keep`, `-k` | Whether or not to keep temporary files. By default, files will be deleted if all goes well but remain when an error occurs. By specifying --keep true, the temporary files will always be retained, whereas --keep false will always delete them. The temporary directory can be overwritten by setting defining a VIASH_TEMP directory. | String |


## viash ns build

Build a namespace from many viash config files.  

  

**Usage:**  

`viash ns build [-n nmspc] [-s src] [-t target] [-p docker] [--setup] [---push] [--parallel] [--flatten]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--query`, `-q` | Filter which components get selected by name and namespace. Can be a regex. Example: "^mynamespace/component1\$". | String |
| `--query_namespace`, `-n` | Filter which namespaces get selected by namespace. Can be a regex. Example: "^mynamespace\$". | String |
| `--query_name` | Filter which components get selected by name. Can be a regex. Example: "^component1". | String |
| `--src`, `-s` |  A source directory containing viash config files, possibly structured in a hierarchical folder structure. Default: src/. | String |
| `--platform`, `-p` | Acts as a regular expression to filter the platform ids specified in the found config files. If this is not provided, all platforms will be used. If no platforms are defined in a config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--parallel`, `-l` | Whether or not to run the process in parallel. | Boolean |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--target`, `-t` | A target directory to build the executables into. Default: target/. | String |
| `--setup` | Which setup strategy for creating the container to use [Docker Platform only]. | String |
| `--push` | Whether or not to push the container to a Docker registry [Docker Platform only]. | Boolean |
| `--write_meta`, `-w` | Write out some meta information to RESOURCES_DIR/viash.yaml at the end. | Boolean |
| `--flatten`, `-f` | Flatten the target builds, handy for building one platform to a bin directory. | Boolean |


## viash ns test

Test a namespace containing many viash config files.  

  

**Usage:**  

`viash ns test [-n nmspc] [-s src] [-p docker] [--parallel] [--tsv file.tsv] [--append]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--query`, `-q` | Filter which components get selected by name and namespace. Can be a regex. Example: "^mynamespace/component1\$". | String |
| `--query_namespace`, `-n` | Filter which namespaces get selected by namespace. Can be a regex. Example: "^mynamespace\$". | String |
| `--query_name` | Filter which components get selected by name. Can be a regex. Example: "^component1". | String |
| `--src`, `-s` |  A source directory containing viash config files, possibly structured in a hierarchical folder structure. Default: src/. | String |
| `--platform`, `-p` | Acts as a regular expression to filter the platform ids specified in the found config files. If this is not provided, all platforms will be used. If no platforms are defined in a config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--parallel`, `-l` | Whether or not to run the process in parallel. | Boolean |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--keep`, `-k` | Whether or not to keep temporary files. By default, files will be deleted if all goes well but remain when an error occurs. By specifying --keep true, the temporary files will always be retained, whereas --keep false will always delete them. The temporary directory can be overwritten by setting defining a VIASH_TEMP directory. | String |
| `--tsv`, `-t` | Path to write a summary of the test results to. | String |
| `--append`, `-a` | Append to tsv instead of overwrite | Boolean |


## viash ns list

List a namespace containing many viash config files.  

  

**Usage:**  

`viash ns list [-n nmspc] [-s src] [-p docker]`  

  

| Argument | Description | Type |
|-|:----|-:
| `--query`, `-q` | Filter which components get selected by name and namespace. Can be a regex. Example: "^mynamespace/component1\$". | String |
| `--query_namespace`, `-n` | Filter which namespaces get selected by namespace. Can be a regex. Example: "^mynamespace\$". | String |
| `--query_name` | Filter which components get selected by name. Can be a regex. Example: "^component1". | String |
| `--src`, `-s` |  A source directory containing viash config files, possibly structured in a hierarchical folder structure. Default: src/. | String |
| `--platform`, `-p` | Acts as a regular expression to filter the platform ids specified in the found config files. If this is not provided, all platforms will be used. If no platforms are defined in a config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--parallel`, `-l` | Whether or not to run the process in parallel. | Boolean |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--format`, `-f` | Which output format to use. | String |


## viash config view

View the config file after parsing.  

  

**Usage:**  

`viash config view config.vsh.yaml`  

  

| Argument | Description | Type |
|-|:----|-:
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. | String |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |
| `--format`, `-f` | Which output format to use. | String |


## viash config inject

Inject a Viash header into the main script of a Viash component.  

  

**Usage:**  

`viash config inject config.vsh.yaml`  

  

| Argument | Description | Type |
|-|:----|-:
| `--platform`, `-p` | Specifies which platform amongst those specified in the config to use. If this is not provided, the first platform will be used. If no platforms are defined in the config, the native platform will be used. In addition, the path to a platform yaml file can also be specified. | String |
| `--config` | A viash config file (example: config.vsh.yaml). This argument can also be a script with the config as a header. | String |
| `--config_mod`, `-c` | Modify a viash config at runtime using a custom DSL. For more information, see the online documentation. | List[String] |


