---
title: "Viash 0.5.13"
subtitle: "Added overriding of the container registry for the VDSL3 + VDSL3 bug fixes"
date: 2022-06-10
categories:
  - New Release
author: Viash Team
---

## What's new?

VDSL3 gets even more improvements and bug fixes.

## Full changelog

### NEW FUNCTIONALITY

* `NextflowVdsl3Platform`: Allow overriding the container registry of all Viash components by 
  setting the `params.override_container_registry` value. Only works for auto-derived image names.

### MAJOR CHANGES

* `Functionality`: renamed `tests` to `test_resources`.
  Backwards compatibility provided but a notification message is displayed on the console.

### MINOR CHANGES

* `Functionality` and `viash ns`: Added `.enabled` in functionality, set to `true` by default.
  Filter for disabled components in namespace commands.

* `DockerPlatform`: Add org.opencontainers.image annotations to built docker images.

* `Functionality`: when defining text resources, permit defining `path` instead of `dest`.
  If both `dest` and `path` are unset, use a default file name depending on the resource type, such as `script.sh` or `text.txt`.

* `viash build`: Errors are printed in red.

### BUG FIXES

* `NextflowVdsl3Platform`: Undefined input files should not inject a `VIASH_PAR_*` variable when `multiple: true`.

* `NextflowVdsl3Platform`: Make injected resources dir absolute.

* `NextflowVdsl3Platform`: Fix escaping of triple single quotes.

* `NextflowVdsl3Platform`: Also apply auto.simplifyInput to Lists.

* `DockerPlatform`: added a `test_setup` that allows adding apt/apk/... setup requirements.
  These are only executed when running tests.

