structure:
  'Config': ./index
  'PackageConfig': ../packageConfig/index
  'BuildInfo': ./buildInfo
  'EnvironmentVariables': ../environmentVariables/index

  'Functionality': ./functionality
  'Author': ./author
  'ComputationalRequirements': ./computationalRequirements
  'ArgumentGroup': ./argumentGroup
  'Links': ./links
  'References': ./references

  'Platform': ./platforms/index
  'NativePlatform': ./platforms/native/index
  'DockerPlatform': ./platforms/docker/index
  'NextflowPlatform': ./platforms/nextflow/index

  'Engine': ./engines/index
  'NativeEngine': ./engines/native/index
  'DockerEngine': ./engines/docker/index

  'Runner': ./runners/index
  'ExecutableRunner': ./runners/executable/index
  'NextflowRunner': ./runners/nextflow/index

  'Argument': ./arguments/index
  'BooleanFalseArgument': ./arguments/boolean_false
  'BooleanArgument': ./arguments/boolean
  'BooleanTrueArgument': ./arguments/boolean_true
  'DoubleArgument': ./arguments/double
  'FileArgument': ./arguments/file
  'IntegerArgument': ./arguments/integer
  'LongArgument': ./arguments/long
  'StringArgument': ./arguments/string
  
  'Requirements': ./engines/docker/setup/index
  'ApkRequirements': ./engines/docker/setup/apkRequirements
  'AptRequirements': ./engines/docker/setup/aptRequirements
  'DockerRequirements': ./engines/docker/setup/dockerRequirements
  'JavaScriptRequirements': ./engines/docker/setup/javascriptRequirements
  'PythonRequirements': ./engines/docker/setup/pythonRequirements
  'RRequirements': ./engines/docker/setup/rRequirements
  'RubyRequirements': ./engines/docker/setup/rubyRequirements
  'YumRequirements': ./engines/docker/setup/yumRequirements

  'Resource': ./resources/index
  'CSharpScript': ./resources/cSharpScript
  'PythonScript': ./resources/pythonScript
  'PlainFile': ./resources/plainFile
  'BashScript': ./resources/bashScript
  'ScalaScript': ./resources/scalaScript
  'NextflowScript': ./resources/nextflowScript
  'RScript': ./resources/rScript
  'Executable': ./resources/executable
  'JavaScriptScript': ./resources/javaScriptScript

  'NextflowDirectives': ./runners/nextflow/directives
  'NextflowAuto': ./runners/nextflow/auto
  'NextflowConfig': ./runners/nextflow/config

  'Dependency': ./dependencies/index
  'Repository': ./repositories/index
  'LocalRepository': 
  'GitRepository': 
  'GithubRepository': 
  'ViashhubRepository': 

  'RepositoryWithName': 
  'LocalRepositoryWithName': ./repositories/localRepository
  'GitRepositoryWithName': ./repositories/gitRepository
  'GithubRepositoryWithName': ./repositories/githubRepository
  'ViashhubRepositoryWithName': ./repositories/viashhubRepository

order:
  'Config': 20
  'Project': 30

  #'Functionality': 10
  #'Platform': 20
  #'BuildInfo': 30
  
  'NativePlatform': 10
  'DockerPlatform': 20
  'NextflowPlatform': 30

keywords:
  mykeyword: /reference/config.html
  namespace: /guide/project/structure.html#grouping-components-in-namespaces
  config_mod: /reference/config_mods/#
  docker_setup_strategy: /guide/component/add-dependencies.html#step-3-rebuild-docker-image
  docker_registry: /reference/config/engines/docker/#registry
  docker_tag: /reference/config/engines/docker/#tag
  resources: /reference/config/resources/#
  unit_testing: /guide/component/unit-testing.html
  scripting_languages: /guide/component/create-component.html#create-a-script
  argument_groups: /reference/config/#argument_groups
  author: /reference/config/author.html
  computational_requirements: /reference/config/computationalRequirements.html
  apk_req: /reference/config/engines/docker/setup/apkRequirements.html
  apt_req: /reference/config/engines/docker/setup/aptRequirements.html
  docker_req: /reference/config/engines/docker/setup/dockerRequirements.html
  javascript_req: /reference/config/engines/docker/setup/javascriptRequirements.html
  python_req: /reference/config/engines/docker/setup/pythonRequirements.html
  r_req: /reference/config/engines/docker/setup/rRequirements.html
  ruby_req: /reference/config/engines/docker/setup/rubyRequirements.html
  yum_req: /reference/config/engines/docker/setup/yumRequirements.html
  argument: /reference/config/arguments/#
  arg_string: /reference/config/arguments/string.html
  arg_file: /reference/config/arguments/file.html
  arg_integer: /reference/config/arguments/integer.html
  arg_double: /reference/config/arguments/double.html
  arg_float: /reference/config/arguments/float.html
  arg_boolean: /reference/config/arguments/boolean.html
  arg_boolean_true: /reference/config/arguments/boolean_true.html
  arg_boolean_false: /reference/config/arguments/boolean_false.html
  functionality: /reference/config/functionality.html
  platform_native: /reference/config/platforms/native/#
  platform_docker: /reference/config/platforms/docker/#
  platform_nextflow: /reference/config/platforms/nextflow/#
  nextflow_directives: /reference/config/platforms/nextflow/directives.html
  nextflow_auto: /reference/config/platforms/nextflow/auto.html
  nextflow_config: /reference/config/platforms/nextflow/config.html
  native_engine: /reference/config/engines/native/#
  docker_engine: /reference/config/engines/docker/#
  executable_runner: /reference/config/runners/executable/#
  nextflow_runner: /reference/config/runners/nextflow/#
  project_config: /reference/projectConfig/#

  repository: /reference/config/repositories/#
  repo_local: /reference/config/repositories/localRepository.html
  repo_git: /reference/config/repositories/gitRepository.html
  repo_github: /reference/config/repositories/githubRepository.html
  repo_vsh: /reference/config/repositories/viashhubRepository.html
