name: generate_reference_main_index_page
description: |
  The script reads the viash cli & config schema json schemas and assembles it to the main reference page listing
arguments:
  - name: "--output"
    type: file
    alternatives: "-o"
    direction: output
    default: 'reference/reference.yml'
    description: Path to use to store the index page listing
resources:
  - type: python_script
    path: script.py
engines:
  - type: native
runners:
  - type: executable
