---
title: "Viash 0.5.2"
subtitle: "This is a small release containing two small features and a bug fix."
date: 2021/08/16
categories:
  - New Release
author: Viash Team
---

## What's new?

This is a small release containing two small features and a bug fix.
The new `run_args` field allows you to add [docker run](https://docs.docker.com/engine/api/commandline/run/) arguments to the [Docker platform](/api/config/platform-docker/) section of a [config file](/api/config/config/). For example:

```yaml
platforms:
  - type: docker
  image: bash:4.0
  run_args: "--expose 127.0.0.1:80:8080/tcp --env MY_ENV_VAR=foo"
```

There's also a new field for the [Nextflow platform](/api/config/platform-nextflow/): `separate_multiple_outputs`. By default, this is set to `true` and separates the outputs generated by a Nextflow component with multiple outputs as separate events on the channel. You can now choose to disable this behaviour:

```yaml
platforms:
  - type: nextflow
    publish: true
    separate_multiple_outputs: false
```

## Full changelog:

### MINOR CHANGES

* `DockerPlatform`: Added `run_args` field to allow setting `docker run` arguments.

* `NextFlowPlatform`: Added argument `separate_multiple_outputs` to allow not separating the outputs generated by a
  component with multiple outputs as separate events on the channel.

### BUG FIXES

* `IO`: Allow overwriting directory resources upon rebuild.
