---
title: "Nextflow Vdsl3 Platform"
search: true
order: 30
---

Next-gen platform for generating NextFlow VDSL3 modules.

**Example:**

```yaml
platforms:
  - type: nextflow
    directives:
      label: [lowcpu, midmem]

```

## auto

**Type**: `NextflowAuto`

**Default**: `simplifyInput: true
simplifyOutput: true
transcript: false
publish: false
`

[Automated processing flags](/reference/config/platforms/nextflow/auto.html) which can be toggled on or off:

| Flag | Description | Default |
|---|---------|----|
| `simplifyInput` | If `true`, an input tuple only containing only a single File (e.g. `["foo", file("in.h5ad")]`) is automatically transformed to a map (i.e. `["foo", [ input: file("in.h5ad") ] ]`). | `true` |
| `simplifyOutput` | If `true`, an output tuple containing a map with a File (e.g. `["foo", [ output: file("out.h5ad") ] ]`) is automatically transformed to a map (i.e. `["foo", file("out.h5ad")]`). | `true` |
| `transcript` | If `true`, the module's transcripts from `work/` are automatically published to `params.transcriptDir`. If not defined, `params.publishDir + "/_transcripts"` will be used. Will throw an error if neither are defined. | `false` |
| `publish` | If `true`, the module's outputs are automatically published to `params.publishDir`.  Will throw an error if `params.publishDir` is not defined. | `false` |



**Example:**

```yaml
auto:
  publish: true
```

## config

**Type**: `NextflowConfig`

**Default**: `A series of default labels to specify memory and cpu constraints`

Allows tweaking how the [Nextflow Config](/reference/config/platforms/nextflow/config.html) file is generated.

## container

**Type**: `String`

**Default**: `docker`

Specifies the Docker platform id to be used to run Nextflow.

## debug

**Type**: `Boolean`

**Default**: `False`

Whether or not to print debug messages.

## directives

**Type**: `NextflowDirectives`

**Default**: `Empty`

[Directives](/reference/config/platforms/nextflow/directives.html) are optional settings that affect the execution of the process. These mostly match up with the Nextflow counterparts.  


**Example:**

```yaml
directives:
  container: rocker/r-ver:4.1
  label: highcpu
  cpus: 4
  memory: 16 GB
```

## id

**Type**: `String`

**Default**: `nextflow`

Every platform can be given a specific id that can later be referred to explicitly when running or building the Viash component.

**Example:**

```yaml
id: foo
```

## type

**Type**: `String`

Specifies the type of the platform.
