---
title: Terminology
search: true
execute:
  echo: false
  output: asis
---

The reference below serves as a reference for the terms used throughout the guides and other pages.  

| Term | Description |
|----|----|
|   Viash   |     A script code wrapper for building modular software components that serve as building blocks to develop (Nextflow) data pipelines.         |
|    Component  |     At minimum, the combination of a [script](/documentation/guide/component/languages.html) and a [config file](/documentation/reference/config/overview.html). This can also include any needed resources and [unit tests](/documentation/guide/component/unit-testing.html).          |
|    [Viash config](/documentation/reference/config/overview.html)   |       A YAML based file that holds all of the parameters needed to create a component.      |
|    Resources |       Tools, helper scripts, templates and other files the component depends on to work.     |
|    [Unit test](/documentation/guide/component/unit-testing.html) |       A small block of code to test a component.    |
|    Build target |       An executable or a VDSL3 module that's generated by Viash.    |
|    [(VDSL3) Module](/documentation/guide/building-block/nextflow/building-running.html) |       A [Nextflow](https://www.nextflow.io/) module generated by Viash.    |
|    (Viash) Executable |       An executable script generated for the [Native](/documentation/guide/building-block/native-building-running.html) or [Docker](/documentation/guide/building-block/docker/building-running.html) platform.    |
|    (Docker) Image |       A standard unit of software that packages up the OS, code and its dependencies so the application runs quickly and reliably from one computing environment to another.     |
|    (Docker) Container |       An instance of a Docker image.     |
|    Platform |      The platform(s) targeted by a component. We currently support Native, Docker and Nextflow.     |
: {tbl-colwidths="[25,75]"}