---
title: "Guide"
# subtitle: Comprehensive guide to using Viash.
page-layout: article
anchor-sections: false
search: false
# listing:
#   id: guide-links
#   template: ../ejs/links.ejs
#   contents: guide.yml
---

<!-- ::: {#guide-links .column-screen-inset-right style="max-width: 850px;"}
::: -->

### Components

A Viash component is a combination of a [script](/guide/component/languages.html), a [config file](/reference/config/overview.html) and an optional [unit test](/guide/component/unit-testing.html). We've split up the component guides per build target in order of complexity:

- [Native](/guide/component/creation/native.html)
- [Docker](/guide/component/creation/docker.html)
- [Nextflow](/guide/component/creation/nextflow.html)

### Build targets

Viash generates build targets based on your component, these are standardized executables and modules:

- [Native](/guide/building-block/native-building-running.html): An executable that runs on your local machine
- [Docker](/guide/building-block/docker/building-running.html): An executable that runs in a generated docker container
- [Nextflow](/guide/building-block/nextflow/building-running.html): A Nextflow module that can be incorporated in a Nextflow pipeline
 
### Data workflows

<!-- #### Scripted pipeline -->

#### Nextflow pipeline

Learn how to make a VDSL3 script that utilizes Viash-generated modules to create a pipeline:

- [Basic pipeline](/guide/data-workflow/nextflow-pipeline/pipeline-basics.html): Create a Nextflow pipeline using a single Viash component to learn the basics.
- [Advanced pipeline](/guide/data-workflow/nextflow-pipeline/pipeline-advanced.html): Covers how to chain multiple Viash-generated modules together into a Nextflow pipeline.

<!-- ### Projects -->

