---
title: "C# Script"
search: true
---

An executable C# script.
When defined in resources, only the first entry will be executed when running the built component or when running `viash run`.
When defined in test_resources, all entries will be executed during `viash test`.

## dest

**Type**: `String`

**Default**: `Empty`

Resulting filename of the resource. From within a script, the file can be accessed at `meta["resources_dir"] + "/" + dest`. If unspecified, `dest` will be set to the basename of the `path` parameter.

## is_executable

**Type**: `Boolean`

**Default**: `Empty`

Whether the resulting resource file should be made executable.

## path

**Type**: `String`

**Default**: `Empty`

The path of the input file. Can be a relative or an absolute path, or a URI. Mutually exclusive with `text`.

## text

**Type**: `String`

**Default**: `Empty`

The content of the resulting file specified as a string. Mutually exclusive with `path`.

## type

**Type**: `String`

Specifies the resource as a C# script.
