---
title: "Boolean True"
search: true
---

An argument of the `boolean_true` type acts like a `boolean` flag with a default value of `false`. When called as an argument it sets the `boolean` to `true`.

**Example:**

```yaml
arguments:
  - name: --silent
    type: boolean_true
    description: Ignore console output
    alternatives: ["-s"]

```

## alternatives

**Type**: `String` / `List of String`

**Default**: `Empty`

List of alternative format variations for this argument.

## description

**Type**: `String`

**Default**: `Empty`

A description of the argument. This is only used for documentation. Multiline descriptions are supported.

**Example:**

```yaml
description: |
  A (multiline) description of the purpose of
  this argument.
```

## info

**Type**: `Json`

**Default**: `Empty`

Structured information. Can be any shape: a string, vector, map or even nested map.

**Example:**

```yaml
info:
  category: cat1
  labels: [one, two, three]
```

## label

**Type**: `String`

**Default**: `Empty`

A clean version of the argument's name. This is only used for documentation.

**Example:**

```yaml
label: "My argument"
```

## name

**Type**: `String`

The name of the argument. Can be in the formats `--silent`, `-s` or `silent`. The number of dashes determines how values can be passed:  

  - `--silent` is a long option, which can be passed with `executable_name --silent`
  - `-s` is a short option, which can be passed with `executable_name -s`
  - `silent` is an argument, which can be passed with `executable_name silent`  


## summary

**Type**: `String`

**Default**: `Empty`

A one-sentence summary of the argument. This is only used for documentation.

**Example:**

```yaml
summary: "This argument sets XYZ."
```

## type

**Type**: `String`

Specifies the type of the argument.
