---
title: "Local Repository"
search: true
---

Defines a locally present and available repository.
This can be used to define components from the same code base as the current component.
Alternatively, this can be used to refer to a code repository present on the local hard-drive instead of fetchable remotely, for example during development.


**Example:**

Refer to a local code repository under `additional_code/src` referenced to the Viash Project Config file.

```yaml
name: my_local_code
type: local
path: /additional_code/src

```

## name

**Type**: `String`

The identifier used to refer to this repository from dependencies.

## path

**Type**: `String`

**Default**: `Empty`

Defines a subfolder of the repository to use as base to look for the dependency components.

## tag

**Type**: `String`

**Default**: `Empty`

Defines which version of the dependency component to use. Typically this can be a specific tag, branch or commit hash.

## type

**Type**: `String`

Defines the repository as a locally present and available repository.
